name: Build OpenBIOS-ATI
on: [push, workflow_dispatch]

jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Tools
        run: sudo apt-get update && sudo apt-get install -y gcc-powerpc-linux-gnu make xxd xsltproc fcode-utils
      - name: Configure Build
        run: ./config/scripts/switch-arch qemu-ppc
      - name: Build PPC Binary
        run: make V=1 CROSS_COMPILE=powerpc-linux-gnu-
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openbios-ppc-custom
          path: obj-ppc/openbios-qemu.elf
      - name: Publish Firmware Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: firmware-latest
          name: Latest OpenBIOS Firmware
          prerelease: true
          files: obj-ppc/openbios-qemu.elf
