name: Build OpenBIOS-ATI
on: [push, workflow_dispatch]

jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Tools
        run: sudo apt-get update && sudo apt-get install -y gcc-powerpc-linux-gnu gcc-powerpc64-linux-gnu make xxd xsltproc fcode-utils
      - name: Configure PPC Build
        run: ./config/scripts/switch-arch qemu-ppc
      - name: Build PPC Binary
        run: make V=1 CROSS_COMPILE=powerpc-linux-gnu-
      - name: Configure PPC64 Build
        run: ./config/scripts/switch-arch qemu-ppc64
        env:
          CROSS_COMPILE: powerpc64-linux-gnu-
      - name: Build PPC64 Binary
        run: make V=1 CROSS_COMPILE=powerpc64-linux-gnu-
      - name: Upload PPC Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openbios-ppc-custom
          path: obj-ppc/openbios-qemu.elf
      - name: Upload PPC64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openbios-ppc64-custom
          path: obj-ppc64/openbios-qemu.elf
      - name: Publish Firmware Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: firmware-latest
          name: Latest OpenBIOS Firmware
          prerelease: true
          files: |
            obj-ppc/openbios-qemu.elf
            obj-ppc64/openbios-qemu.elf
